### ISSUE TITLE
HAProxy failed to load balance for `docker-compose scale`

### ISSUE THREAD

**Issue by twang2218** [gesellix/docker-haproxy-network#2]
Hi,

I tried something similar, but instead of using `docker run`, I choose `docker-compose` for better control and scalability. Here is the `docker-compose.yml`

``` yaml
version: '2'
services:
    haproxy:
        image: haproxy:latest
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - "80:80"
    app:
        build: ./app/.
    syslog:
        image: bobrik/syslog-ng:latest
        volumes:
            - ./log:/var/log/syslog-ng
```

Here is the `haproxy.cfg`

```
global
    log syslog daemon

defaults
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

resolvers docker_dns
  nameserver dns "127.0.0.11:53"
  timeout retry   1s
  hold valid 1s

listen tcp_proxy
    mode tcp
    bind :80
    option tcplog
    log global
    server app app:8000 check resolvers docker_dns resolve-prefer ipv4
```

The result is same if I `docker-compose restart app`, the haproxy will be notified for the ip changes. However, it's failed for the scaling.

If I run `docker-compose scale app=10`, the haproxy will only use the previous dns record it resolved, and never respect the `hold valid 1s` settings and resolve it again.

Do you have any idea why haproxy not resolve the app address again after the `1s`?
